// File generated from our OpenAPI spec by Stainless.

package com.branddev.api.models.brand

import com.branddev.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BrandRetrieveByIsinResponseTest {

    @Test
    fun create() {
        val brandRetrieveByIsinResponse =
            BrandRetrieveByIsinResponse.builder()
                .brand(
                    BrandRetrieveByIsinResponse.Brand.builder()
                        .address(
                            BrandRetrieveByIsinResponse.Brand.Address.builder()
                                .city("city")
                                .country("country")
                                .countryCode("country_code")
                                .postalCode("postal_code")
                                .stateCode("state_code")
                                .stateProvince("state_province")
                                .street("street")
                                .build()
                        )
                        .addBackdrop(
                            BrandRetrieveByIsinResponse.Brand.Backdrop.builder()
                                .addColor(
                                    BrandRetrieveByIsinResponse.Brand.Backdrop.Color.builder()
                                        .hex("hex")
                                        .name("name")
                                        .build()
                                )
                                .resolution(
                                    BrandRetrieveByIsinResponse.Brand.Backdrop.Resolution.builder()
                                        .aspectRatio(0.0)
                                        .height(0L)
                                        .width(0L)
                                        .build()
                                )
                                .url("url")
                                .build()
                        )
                        .addColor(
                            BrandRetrieveByIsinResponse.Brand.Color.builder()
                                .hex("hex")
                                .name("name")
                                .build()
                        )
                        .description("description")
                        .domain("domain")
                        .email("email")
                        .industries(
                            BrandRetrieveByIsinResponse.Brand.Industries.builder()
                                .addEic(
                                    BrandRetrieveByIsinResponse.Brand.Industries.Eic.builder()
                                        .industry(
                                            BrandRetrieveByIsinResponse.Brand.Industries.Eic
                                                .Industry
                                                .AEROSPACE_DEFENSE
                                        )
                                        .subindustry(
                                            BrandRetrieveByIsinResponse.Brand.Industries.Eic
                                                .Subindustry
                                                .DEFENSE_SYSTEMS_MILITARY_HARDWARE
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .isNsfw(true)
                        .links(
                            BrandRetrieveByIsinResponse.Brand.Links.builder()
                                .blog("blog")
                                .careers("careers")
                                .contact("contact")
                                .pricing("pricing")
                                .privacy("privacy")
                                .terms("terms")
                                .build()
                        )
                        .addLogo(
                            BrandRetrieveByIsinResponse.Brand.Logo.builder()
                                .addColor(
                                    BrandRetrieveByIsinResponse.Brand.Logo.Color.builder()
                                        .hex("hex")
                                        .name("name")
                                        .build()
                                )
                                .mode(BrandRetrieveByIsinResponse.Brand.Logo.Mode.LIGHT)
                                .resolution(
                                    BrandRetrieveByIsinResponse.Brand.Logo.Resolution.builder()
                                        .aspectRatio(0.0)
                                        .height(0L)
                                        .width(0L)
                                        .build()
                                )
                                .type(BrandRetrieveByIsinResponse.Brand.Logo.Type.ICON)
                                .url("url")
                                .build()
                        )
                        .phone("phone")
                        .slogan("slogan")
                        .addSocial(
                            BrandRetrieveByIsinResponse.Brand.Social.builder()
                                .type("type")
                                .url("url")
                                .build()
                        )
                        .stock(
                            BrandRetrieveByIsinResponse.Brand.Stock.builder()
                                .exchange("exchange")
                                .ticker("ticker")
                                .build()
                        )
                        .title("title")
                        .build()
                )
                .code(0L)
                .status("status")
                .build()

        assertThat(brandRetrieveByIsinResponse.brand())
            .contains(
                BrandRetrieveByIsinResponse.Brand.builder()
                    .address(
                        BrandRetrieveByIsinResponse.Brand.Address.builder()
                            .city("city")
                            .country("country")
                            .countryCode("country_code")
                            .postalCode("postal_code")
                            .stateCode("state_code")
                            .stateProvince("state_province")
                            .street("street")
                            .build()
                    )
                    .addBackdrop(
                        BrandRetrieveByIsinResponse.Brand.Backdrop.builder()
                            .addColor(
                                BrandRetrieveByIsinResponse.Brand.Backdrop.Color.builder()
                                    .hex("hex")
                                    .name("name")
                                    .build()
                            )
                            .resolution(
                                BrandRetrieveByIsinResponse.Brand.Backdrop.Resolution.builder()
                                    .aspectRatio(0.0)
                                    .height(0L)
                                    .width(0L)
                                    .build()
                            )
                            .url("url")
                            .build()
                    )
                    .addColor(
                        BrandRetrieveByIsinResponse.Brand.Color.builder()
                            .hex("hex")
                            .name("name")
                            .build()
                    )
                    .description("description")
                    .domain("domain")
                    .email("email")
                    .industries(
                        BrandRetrieveByIsinResponse.Brand.Industries.builder()
                            .addEic(
                                BrandRetrieveByIsinResponse.Brand.Industries.Eic.builder()
                                    .industry(
                                        BrandRetrieveByIsinResponse.Brand.Industries.Eic.Industry
                                            .AEROSPACE_DEFENSE
                                    )
                                    .subindustry(
                                        BrandRetrieveByIsinResponse.Brand.Industries.Eic.Subindustry
                                            .DEFENSE_SYSTEMS_MILITARY_HARDWARE
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .isNsfw(true)
                    .links(
                        BrandRetrieveByIsinResponse.Brand.Links.builder()
                            .blog("blog")
                            .careers("careers")
                            .contact("contact")
                            .pricing("pricing")
                            .privacy("privacy")
                            .terms("terms")
                            .build()
                    )
                    .addLogo(
                        BrandRetrieveByIsinResponse.Brand.Logo.builder()
                            .addColor(
                                BrandRetrieveByIsinResponse.Brand.Logo.Color.builder()
                                    .hex("hex")
                                    .name("name")
                                    .build()
                            )
                            .mode(BrandRetrieveByIsinResponse.Brand.Logo.Mode.LIGHT)
                            .resolution(
                                BrandRetrieveByIsinResponse.Brand.Logo.Resolution.builder()
                                    .aspectRatio(0.0)
                                    .height(0L)
                                    .width(0L)
                                    .build()
                            )
                            .type(BrandRetrieveByIsinResponse.Brand.Logo.Type.ICON)
                            .url("url")
                            .build()
                    )
                    .phone("phone")
                    .slogan("slogan")
                    .addSocial(
                        BrandRetrieveByIsinResponse.Brand.Social.builder()
                            .type("type")
                            .url("url")
                            .build()
                    )
                    .stock(
                        BrandRetrieveByIsinResponse.Brand.Stock.builder()
                            .exchange("exchange")
                            .ticker("ticker")
                            .build()
                    )
                    .title("title")
                    .build()
            )
        assertThat(brandRetrieveByIsinResponse.code()).contains(0L)
        assertThat(brandRetrieveByIsinResponse.status()).contains("status")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val brandRetrieveByIsinResponse =
            BrandRetrieveByIsinResponse.builder()
                .brand(
                    BrandRetrieveByIsinResponse.Brand.builder()
                        .address(
                            BrandRetrieveByIsinResponse.Brand.Address.builder()
                                .city("city")
                                .country("country")
                                .countryCode("country_code")
                                .postalCode("postal_code")
                                .stateCode("state_code")
                                .stateProvince("state_province")
                                .street("street")
                                .build()
                        )
                        .addBackdrop(
                            BrandRetrieveByIsinResponse.Brand.Backdrop.builder()
                                .addColor(
                                    BrandRetrieveByIsinResponse.Brand.Backdrop.Color.builder()
                                        .hex("hex")
                                        .name("name")
                                        .build()
                                )
                                .resolution(
                                    BrandRetrieveByIsinResponse.Brand.Backdrop.Resolution.builder()
                                        .aspectRatio(0.0)
                                        .height(0L)
                                        .width(0L)
                                        .build()
                                )
                                .url("url")
                                .build()
                        )
                        .addColor(
                            BrandRetrieveByIsinResponse.Brand.Color.builder()
                                .hex("hex")
                                .name("name")
                                .build()
                        )
                        .description("description")
                        .domain("domain")
                        .email("email")
                        .industries(
                            BrandRetrieveByIsinResponse.Brand.Industries.builder()
                                .addEic(
                                    BrandRetrieveByIsinResponse.Brand.Industries.Eic.builder()
                                        .industry(
                                            BrandRetrieveByIsinResponse.Brand.Industries.Eic
                                                .Industry
                                                .AEROSPACE_DEFENSE
                                        )
                                        .subindustry(
                                            BrandRetrieveByIsinResponse.Brand.Industries.Eic
                                                .Subindustry
                                                .DEFENSE_SYSTEMS_MILITARY_HARDWARE
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .isNsfw(true)
                        .links(
                            BrandRetrieveByIsinResponse.Brand.Links.builder()
                                .blog("blog")
                                .careers("careers")
                                .contact("contact")
                                .pricing("pricing")
                                .privacy("privacy")
                                .terms("terms")
                                .build()
                        )
                        .addLogo(
                            BrandRetrieveByIsinResponse.Brand.Logo.builder()
                                .addColor(
                                    BrandRetrieveByIsinResponse.Brand.Logo.Color.builder()
                                        .hex("hex")
                                        .name("name")
                                        .build()
                                )
                                .mode(BrandRetrieveByIsinResponse.Brand.Logo.Mode.LIGHT)
                                .resolution(
                                    BrandRetrieveByIsinResponse.Brand.Logo.Resolution.builder()
                                        .aspectRatio(0.0)
                                        .height(0L)
                                        .width(0L)
                                        .build()
                                )
                                .type(BrandRetrieveByIsinResponse.Brand.Logo.Type.ICON)
                                .url("url")
                                .build()
                        )
                        .phone("phone")
                        .slogan("slogan")
                        .addSocial(
                            BrandRetrieveByIsinResponse.Brand.Social.builder()
                                .type("type")
                                .url("url")
                                .build()
                        )
                        .stock(
                            BrandRetrieveByIsinResponse.Brand.Stock.builder()
                                .exchange("exchange")
                                .ticker("ticker")
                                .build()
                        )
                        .title("title")
                        .build()
                )
                .code(0L)
                .status("status")
                .build()

        val roundtrippedBrandRetrieveByIsinResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(brandRetrieveByIsinResponse),
                jacksonTypeRef<BrandRetrieveByIsinResponse>(),
            )

        assertThat(roundtrippedBrandRetrieveByIsinResponse).isEqualTo(brandRetrieveByIsinResponse)
    }
}
