// File generated from our OpenAPI spec by Stainless.

package com.branddev.api.models.brand

import com.branddev.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BrandRetrieveByTickerResponseTest {

    @Test
    fun create() {
        val brandRetrieveByTickerResponse =
            BrandRetrieveByTickerResponse.builder()
                .brand(
                    BrandRetrieveByTickerResponse.Brand.builder()
                        .address(
                            BrandRetrieveByTickerResponse.Brand.Address.builder()
                                .city("city")
                                .country("country")
                                .countryCode("country_code")
                                .postalCode("postal_code")
                                .stateCode("state_code")
                                .stateProvince("state_province")
                                .street("street")
                                .build()
                        )
                        .addBackdrop(
                            BrandRetrieveByTickerResponse.Brand.Backdrop.builder()
                                .addColor(
                                    BrandRetrieveByTickerResponse.Brand.Backdrop.Color.builder()
                                        .hex("hex")
                                        .name("name")
                                        .build()
                                )
                                .resolution(
                                    BrandRetrieveByTickerResponse.Brand.Backdrop.Resolution
                                        .builder()
                                        .aspectRatio(0.0)
                                        .height(0L)
                                        .width(0L)
                                        .build()
                                )
                                .url("url")
                                .build()
                        )
                        .addColor(
                            BrandRetrieveByTickerResponse.Brand.Color.builder()
                                .hex("hex")
                                .name("name")
                                .build()
                        )
                        .description("description")
                        .domain("domain")
                        .email("email")
                        .isNsfw(true)
                        .addLogo(
                            BrandRetrieveByTickerResponse.Brand.Logo.builder()
                                .addColor(
                                    BrandRetrieveByTickerResponse.Brand.Logo.Color.builder()
                                        .hex("hex")
                                        .name("name")
                                        .build()
                                )
                                .mode(BrandRetrieveByTickerResponse.Brand.Logo.Mode.LIGHT)
                                .resolution(
                                    BrandRetrieveByTickerResponse.Brand.Logo.Resolution.builder()
                                        .aspectRatio(0.0)
                                        .height(0L)
                                        .width(0L)
                                        .build()
                                )
                                .type(BrandRetrieveByTickerResponse.Brand.Logo.Type.ICON)
                                .url("url")
                                .build()
                        )
                        .phone("phone")
                        .slogan("slogan")
                        .addSocial(
                            BrandRetrieveByTickerResponse.Brand.Social.builder()
                                .type("type")
                                .url("url")
                                .build()
                        )
                        .stock(
                            BrandRetrieveByTickerResponse.Brand.Stock.builder()
                                .exchange("exchange")
                                .ticker("ticker")
                                .build()
                        )
                        .title("title")
                        .build()
                )
                .code(0L)
                .status("status")
                .build()

        assertThat(brandRetrieveByTickerResponse.brand())
            .contains(
                BrandRetrieveByTickerResponse.Brand.builder()
                    .address(
                        BrandRetrieveByTickerResponse.Brand.Address.builder()
                            .city("city")
                            .country("country")
                            .countryCode("country_code")
                            .postalCode("postal_code")
                            .stateCode("state_code")
                            .stateProvince("state_province")
                            .street("street")
                            .build()
                    )
                    .addBackdrop(
                        BrandRetrieveByTickerResponse.Brand.Backdrop.builder()
                            .addColor(
                                BrandRetrieveByTickerResponse.Brand.Backdrop.Color.builder()
                                    .hex("hex")
                                    .name("name")
                                    .build()
                            )
                            .resolution(
                                BrandRetrieveByTickerResponse.Brand.Backdrop.Resolution.builder()
                                    .aspectRatio(0.0)
                                    .height(0L)
                                    .width(0L)
                                    .build()
                            )
                            .url("url")
                            .build()
                    )
                    .addColor(
                        BrandRetrieveByTickerResponse.Brand.Color.builder()
                            .hex("hex")
                            .name("name")
                            .build()
                    )
                    .description("description")
                    .domain("domain")
                    .email("email")
                    .isNsfw(true)
                    .addLogo(
                        BrandRetrieveByTickerResponse.Brand.Logo.builder()
                            .addColor(
                                BrandRetrieveByTickerResponse.Brand.Logo.Color.builder()
                                    .hex("hex")
                                    .name("name")
                                    .build()
                            )
                            .mode(BrandRetrieveByTickerResponse.Brand.Logo.Mode.LIGHT)
                            .resolution(
                                BrandRetrieveByTickerResponse.Brand.Logo.Resolution.builder()
                                    .aspectRatio(0.0)
                                    .height(0L)
                                    .width(0L)
                                    .build()
                            )
                            .type(BrandRetrieveByTickerResponse.Brand.Logo.Type.ICON)
                            .url("url")
                            .build()
                    )
                    .phone("phone")
                    .slogan("slogan")
                    .addSocial(
                        BrandRetrieveByTickerResponse.Brand.Social.builder()
                            .type("type")
                            .url("url")
                            .build()
                    )
                    .stock(
                        BrandRetrieveByTickerResponse.Brand.Stock.builder()
                            .exchange("exchange")
                            .ticker("ticker")
                            .build()
                    )
                    .title("title")
                    .build()
            )
        assertThat(brandRetrieveByTickerResponse.code()).contains(0L)
        assertThat(brandRetrieveByTickerResponse.status()).contains("status")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val brandRetrieveByTickerResponse =
            BrandRetrieveByTickerResponse.builder()
                .brand(
                    BrandRetrieveByTickerResponse.Brand.builder()
                        .address(
                            BrandRetrieveByTickerResponse.Brand.Address.builder()
                                .city("city")
                                .country("country")
                                .countryCode("country_code")
                                .postalCode("postal_code")
                                .stateCode("state_code")
                                .stateProvince("state_province")
                                .street("street")
                                .build()
                        )
                        .addBackdrop(
                            BrandRetrieveByTickerResponse.Brand.Backdrop.builder()
                                .addColor(
                                    BrandRetrieveByTickerResponse.Brand.Backdrop.Color.builder()
                                        .hex("hex")
                                        .name("name")
                                        .build()
                                )
                                .resolution(
                                    BrandRetrieveByTickerResponse.Brand.Backdrop.Resolution
                                        .builder()
                                        .aspectRatio(0.0)
                                        .height(0L)
                                        .width(0L)
                                        .build()
                                )
                                .url("url")
                                .build()
                        )
                        .addColor(
                            BrandRetrieveByTickerResponse.Brand.Color.builder()
                                .hex("hex")
                                .name("name")
                                .build()
                        )
                        .description("description")
                        .domain("domain")
                        .email("email")
                        .isNsfw(true)
                        .addLogo(
                            BrandRetrieveByTickerResponse.Brand.Logo.builder()
                                .addColor(
                                    BrandRetrieveByTickerResponse.Brand.Logo.Color.builder()
                                        .hex("hex")
                                        .name("name")
                                        .build()
                                )
                                .mode(BrandRetrieveByTickerResponse.Brand.Logo.Mode.LIGHT)
                                .resolution(
                                    BrandRetrieveByTickerResponse.Brand.Logo.Resolution.builder()
                                        .aspectRatio(0.0)
                                        .height(0L)
                                        .width(0L)
                                        .build()
                                )
                                .type(BrandRetrieveByTickerResponse.Brand.Logo.Type.ICON)
                                .url("url")
                                .build()
                        )
                        .phone("phone")
                        .slogan("slogan")
                        .addSocial(
                            BrandRetrieveByTickerResponse.Brand.Social.builder()
                                .type("type")
                                .url("url")
                                .build()
                        )
                        .stock(
                            BrandRetrieveByTickerResponse.Brand.Stock.builder()
                                .exchange("exchange")
                                .ticker("ticker")
                                .build()
                        )
                        .title("title")
                        .build()
                )
                .code(0L)
                .status("status")
                .build()

        val roundtrippedBrandRetrieveByTickerResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(brandRetrieveByTickerResponse),
                jacksonTypeRef<BrandRetrieveByTickerResponse>(),
            )

        assertThat(roundtrippedBrandRetrieveByTickerResponse)
            .isEqualTo(brandRetrieveByTickerResponse)
    }
}
