// File generated from our OpenAPI spec by Stainless.

package com.branddev.api.models.brand

import com.branddev.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

internal class BrandStyleguideResponseTest {

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun create() {
        val brandStyleguideResponse =
            BrandStyleguideResponse.builder()
                .code(0L)
                .domain("domain")
                .status("status")
                .styleguide(
                    BrandStyleguideResponse.Styleguide.builder()
                        .colors(
                            BrandStyleguideResponse.Styleguide.Colors.builder()
                                .accent("accent")
                                .background("background")
                                .text("text")
                                .build()
                        )
                        .components(
                            BrandStyleguideResponse.Styleguide.Components.builder()
                                .button(
                                    BrandStyleguideResponse.Styleguide.Components.Button.builder()
                                        .link(
                                            BrandStyleguideResponse.Styleguide.Components.Button
                                                .Link
                                                .builder()
                                                .backgroundColor("backgroundColor")
                                                .borderColor("borderColor")
                                                .borderRadius("borderRadius")
                                                .borderStyle("borderStyle")
                                                .borderWidth("borderWidth")
                                                .boxShadow("boxShadow")
                                                .color("color")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .padding("padding")
                                                .textDecoration("textDecoration")
                                                .build()
                                        )
                                        .primary(
                                            BrandStyleguideResponse.Styleguide.Components.Button
                                                .Primary
                                                .builder()
                                                .backgroundColor("backgroundColor")
                                                .borderColor("borderColor")
                                                .borderRadius("borderRadius")
                                                .borderStyle("borderStyle")
                                                .borderWidth("borderWidth")
                                                .boxShadow("boxShadow")
                                                .color("color")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .padding("padding")
                                                .textDecoration("textDecoration")
                                                .build()
                                        )
                                        .secondary(
                                            BrandStyleguideResponse.Styleguide.Components.Button
                                                .Secondary
                                                .builder()
                                                .backgroundColor("backgroundColor")
                                                .borderColor("borderColor")
                                                .borderRadius("borderRadius")
                                                .borderStyle("borderStyle")
                                                .borderWidth("borderWidth")
                                                .boxShadow("boxShadow")
                                                .color("color")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .padding("padding")
                                                .textDecoration("textDecoration")
                                                .build()
                                        )
                                        .build()
                                )
                                .card(
                                    BrandStyleguideResponse.Styleguide.Components.Card.builder()
                                        .backgroundColor("backgroundColor")
                                        .borderColor("borderColor")
                                        .borderRadius("borderRadius")
                                        .borderStyle("borderStyle")
                                        .borderWidth("borderWidth")
                                        .boxShadow("boxShadow")
                                        .padding("padding")
                                        .textColor("textColor")
                                        .build()
                                )
                                .build()
                        )
                        .elementSpacing(
                            BrandStyleguideResponse.Styleguide.ElementSpacing.builder()
                                .lg("lg")
                                .md("md")
                                .sm("sm")
                                .xl("xl")
                                .xs("xs")
                                .build()
                        )
                        .shadows(
                            BrandStyleguideResponse.Styleguide.Shadows.builder()
                                .inner("inner")
                                .lg("lg")
                                .md("md")
                                .sm("sm")
                                .xl("xl")
                                .build()
                        )
                        .typography(
                            BrandStyleguideResponse.Styleguide.Typography.builder()
                                .headings(
                                    BrandStyleguideResponse.Styleguide.Typography.Headings.builder()
                                        .h1(
                                            BrandStyleguideResponse.Styleguide.Typography.Headings
                                                .H1
                                                .builder()
                                                .fontFamily("fontFamily")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .letterSpacing("letterSpacing")
                                                .lineHeight("lineHeight")
                                                .build()
                                        )
                                        .h2(
                                            BrandStyleguideResponse.Styleguide.Typography.Headings
                                                .H2
                                                .builder()
                                                .fontFamily("fontFamily")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .letterSpacing("letterSpacing")
                                                .lineHeight("lineHeight")
                                                .build()
                                        )
                                        .h3(
                                            BrandStyleguideResponse.Styleguide.Typography.Headings
                                                .H3
                                                .builder()
                                                .fontFamily("fontFamily")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .letterSpacing("letterSpacing")
                                                .lineHeight("lineHeight")
                                                .build()
                                        )
                                        .h4(
                                            BrandStyleguideResponse.Styleguide.Typography.Headings
                                                .H4
                                                .builder()
                                                .fontFamily("fontFamily")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .letterSpacing("letterSpacing")
                                                .lineHeight("lineHeight")
                                                .build()
                                        )
                                        .build()
                                )
                                .p(
                                    BrandStyleguideResponse.Styleguide.Typography.P.builder()
                                        .fontFamily("fontFamily")
                                        .fontSize("fontSize")
                                        .fontWeight(0.0)
                                        .letterSpacing("letterSpacing")
                                        .lineHeight("lineHeight")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(brandStyleguideResponse.code()).contains(0L)
        assertThat(brandStyleguideResponse.domain()).contains("domain")
        assertThat(brandStyleguideResponse.status()).contains("status")
        assertThat(brandStyleguideResponse.styleguide())
            .contains(
                BrandStyleguideResponse.Styleguide.builder()
                    .colors(
                        BrandStyleguideResponse.Styleguide.Colors.builder()
                            .accent("accent")
                            .background("background")
                            .text("text")
                            .build()
                    )
                    .components(
                        BrandStyleguideResponse.Styleguide.Components.builder()
                            .button(
                                BrandStyleguideResponse.Styleguide.Components.Button.builder()
                                    .link(
                                        BrandStyleguideResponse.Styleguide.Components.Button.Link
                                            .builder()
                                            .backgroundColor("backgroundColor")
                                            .borderColor("borderColor")
                                            .borderRadius("borderRadius")
                                            .borderStyle("borderStyle")
                                            .borderWidth("borderWidth")
                                            .boxShadow("boxShadow")
                                            .color("color")
                                            .fontSize("fontSize")
                                            .fontWeight(0.0)
                                            .padding("padding")
                                            .textDecoration("textDecoration")
                                            .build()
                                    )
                                    .primary(
                                        BrandStyleguideResponse.Styleguide.Components.Button.Primary
                                            .builder()
                                            .backgroundColor("backgroundColor")
                                            .borderColor("borderColor")
                                            .borderRadius("borderRadius")
                                            .borderStyle("borderStyle")
                                            .borderWidth("borderWidth")
                                            .boxShadow("boxShadow")
                                            .color("color")
                                            .fontSize("fontSize")
                                            .fontWeight(0.0)
                                            .padding("padding")
                                            .textDecoration("textDecoration")
                                            .build()
                                    )
                                    .secondary(
                                        BrandStyleguideResponse.Styleguide.Components.Button
                                            .Secondary
                                            .builder()
                                            .backgroundColor("backgroundColor")
                                            .borderColor("borderColor")
                                            .borderRadius("borderRadius")
                                            .borderStyle("borderStyle")
                                            .borderWidth("borderWidth")
                                            .boxShadow("boxShadow")
                                            .color("color")
                                            .fontSize("fontSize")
                                            .fontWeight(0.0)
                                            .padding("padding")
                                            .textDecoration("textDecoration")
                                            .build()
                                    )
                                    .build()
                            )
                            .card(
                                BrandStyleguideResponse.Styleguide.Components.Card.builder()
                                    .backgroundColor("backgroundColor")
                                    .borderColor("borderColor")
                                    .borderRadius("borderRadius")
                                    .borderStyle("borderStyle")
                                    .borderWidth("borderWidth")
                                    .boxShadow("boxShadow")
                                    .padding("padding")
                                    .textColor("textColor")
                                    .build()
                            )
                            .build()
                    )
                    .elementSpacing(
                        BrandStyleguideResponse.Styleguide.ElementSpacing.builder()
                            .lg("lg")
                            .md("md")
                            .sm("sm")
                            .xl("xl")
                            .xs("xs")
                            .build()
                    )
                    .shadows(
                        BrandStyleguideResponse.Styleguide.Shadows.builder()
                            .inner("inner")
                            .lg("lg")
                            .md("md")
                            .sm("sm")
                            .xl("xl")
                            .build()
                    )
                    .typography(
                        BrandStyleguideResponse.Styleguide.Typography.builder()
                            .headings(
                                BrandStyleguideResponse.Styleguide.Typography.Headings.builder()
                                    .h1(
                                        BrandStyleguideResponse.Styleguide.Typography.Headings.H1
                                            .builder()
                                            .fontFamily("fontFamily")
                                            .fontSize("fontSize")
                                            .fontWeight(0.0)
                                            .letterSpacing("letterSpacing")
                                            .lineHeight("lineHeight")
                                            .build()
                                    )
                                    .h2(
                                        BrandStyleguideResponse.Styleguide.Typography.Headings.H2
                                            .builder()
                                            .fontFamily("fontFamily")
                                            .fontSize("fontSize")
                                            .fontWeight(0.0)
                                            .letterSpacing("letterSpacing")
                                            .lineHeight("lineHeight")
                                            .build()
                                    )
                                    .h3(
                                        BrandStyleguideResponse.Styleguide.Typography.Headings.H3
                                            .builder()
                                            .fontFamily("fontFamily")
                                            .fontSize("fontSize")
                                            .fontWeight(0.0)
                                            .letterSpacing("letterSpacing")
                                            .lineHeight("lineHeight")
                                            .build()
                                    )
                                    .h4(
                                        BrandStyleguideResponse.Styleguide.Typography.Headings.H4
                                            .builder()
                                            .fontFamily("fontFamily")
                                            .fontSize("fontSize")
                                            .fontWeight(0.0)
                                            .letterSpacing("letterSpacing")
                                            .lineHeight("lineHeight")
                                            .build()
                                    )
                                    .build()
                            )
                            .p(
                                BrandStyleguideResponse.Styleguide.Typography.P.builder()
                                    .fontFamily("fontFamily")
                                    .fontSize("fontSize")
                                    .fontWeight(0.0)
                                    .letterSpacing("letterSpacing")
                                    .lineHeight("lineHeight")
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
    }

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val brandStyleguideResponse =
            BrandStyleguideResponse.builder()
                .code(0L)
                .domain("domain")
                .status("status")
                .styleguide(
                    BrandStyleguideResponse.Styleguide.builder()
                        .colors(
                            BrandStyleguideResponse.Styleguide.Colors.builder()
                                .accent("accent")
                                .background("background")
                                .text("text")
                                .build()
                        )
                        .components(
                            BrandStyleguideResponse.Styleguide.Components.builder()
                                .button(
                                    BrandStyleguideResponse.Styleguide.Components.Button.builder()
                                        .link(
                                            BrandStyleguideResponse.Styleguide.Components.Button
                                                .Link
                                                .builder()
                                                .backgroundColor("backgroundColor")
                                                .borderColor("borderColor")
                                                .borderRadius("borderRadius")
                                                .borderStyle("borderStyle")
                                                .borderWidth("borderWidth")
                                                .boxShadow("boxShadow")
                                                .color("color")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .padding("padding")
                                                .textDecoration("textDecoration")
                                                .build()
                                        )
                                        .primary(
                                            BrandStyleguideResponse.Styleguide.Components.Button
                                                .Primary
                                                .builder()
                                                .backgroundColor("backgroundColor")
                                                .borderColor("borderColor")
                                                .borderRadius("borderRadius")
                                                .borderStyle("borderStyle")
                                                .borderWidth("borderWidth")
                                                .boxShadow("boxShadow")
                                                .color("color")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .padding("padding")
                                                .textDecoration("textDecoration")
                                                .build()
                                        )
                                        .secondary(
                                            BrandStyleguideResponse.Styleguide.Components.Button
                                                .Secondary
                                                .builder()
                                                .backgroundColor("backgroundColor")
                                                .borderColor("borderColor")
                                                .borderRadius("borderRadius")
                                                .borderStyle("borderStyle")
                                                .borderWidth("borderWidth")
                                                .boxShadow("boxShadow")
                                                .color("color")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .padding("padding")
                                                .textDecoration("textDecoration")
                                                .build()
                                        )
                                        .build()
                                )
                                .card(
                                    BrandStyleguideResponse.Styleguide.Components.Card.builder()
                                        .backgroundColor("backgroundColor")
                                        .borderColor("borderColor")
                                        .borderRadius("borderRadius")
                                        .borderStyle("borderStyle")
                                        .borderWidth("borderWidth")
                                        .boxShadow("boxShadow")
                                        .padding("padding")
                                        .textColor("textColor")
                                        .build()
                                )
                                .build()
                        )
                        .elementSpacing(
                            BrandStyleguideResponse.Styleguide.ElementSpacing.builder()
                                .lg("lg")
                                .md("md")
                                .sm("sm")
                                .xl("xl")
                                .xs("xs")
                                .build()
                        )
                        .shadows(
                            BrandStyleguideResponse.Styleguide.Shadows.builder()
                                .inner("inner")
                                .lg("lg")
                                .md("md")
                                .sm("sm")
                                .xl("xl")
                                .build()
                        )
                        .typography(
                            BrandStyleguideResponse.Styleguide.Typography.builder()
                                .headings(
                                    BrandStyleguideResponse.Styleguide.Typography.Headings.builder()
                                        .h1(
                                            BrandStyleguideResponse.Styleguide.Typography.Headings
                                                .H1
                                                .builder()
                                                .fontFamily("fontFamily")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .letterSpacing("letterSpacing")
                                                .lineHeight("lineHeight")
                                                .build()
                                        )
                                        .h2(
                                            BrandStyleguideResponse.Styleguide.Typography.Headings
                                                .H2
                                                .builder()
                                                .fontFamily("fontFamily")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .letterSpacing("letterSpacing")
                                                .lineHeight("lineHeight")
                                                .build()
                                        )
                                        .h3(
                                            BrandStyleguideResponse.Styleguide.Typography.Headings
                                                .H3
                                                .builder()
                                                .fontFamily("fontFamily")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .letterSpacing("letterSpacing")
                                                .lineHeight("lineHeight")
                                                .build()
                                        )
                                        .h4(
                                            BrandStyleguideResponse.Styleguide.Typography.Headings
                                                .H4
                                                .builder()
                                                .fontFamily("fontFamily")
                                                .fontSize("fontSize")
                                                .fontWeight(0.0)
                                                .letterSpacing("letterSpacing")
                                                .lineHeight("lineHeight")
                                                .build()
                                        )
                                        .build()
                                )
                                .p(
                                    BrandStyleguideResponse.Styleguide.Typography.P.builder()
                                        .fontFamily("fontFamily")
                                        .fontSize("fontSize")
                                        .fontWeight(0.0)
                                        .letterSpacing("letterSpacing")
                                        .lineHeight("lineHeight")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedBrandStyleguideResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(brandStyleguideResponse),
                jacksonTypeRef<BrandStyleguideResponse>(),
            )

        assertThat(roundtrippedBrandStyleguideResponse).isEqualTo(brandStyleguideResponse)
    }
}
